### ISSUE TITLE
EGL/GL synchronisation between threads

### ISSUE THREAD

**Issue by asurdej-comcast** [Metrological/WebKitForWayland#1120]
Another report for OpenGL/EGL synchronisation issue among threads.

Previous reports, PRs:
https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/973
https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/969
https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/976

Issue description:
On Amlogic and Realtek platforms there is an "issue" with threaded rendering. What can be observed by the user is
1) webgl blinking with black screen:
https://github.com/WebPlatformForEmbedded/WPEWebKit/assets/101130014/3906e391-f943-421b-8a64-824ec863d5d6
(from https://webglsamples.org/dynamic-cubemap/dynamic-cubemap.html)
2) Accelerated 2D canvas doesn't draw the latest image but previous one (any change is visible after double redraw), e.g. https://asurdej-comcast.github.io/canvas.html
```
    ctx.fillStyle = colors[colorIdx];
    ctx.fillRect(0,0,c.width, c.height);
```

The outcome of previous discussions was that those platforms have issue with egl/gl synchronization between threads (main, compositor, any other involved?). This was confirmed by Amlogic that the driver doesn't perform any synchronization by its own, we need to explicitly use:
1) glFinish()
2) eglSync/glSync/glFenceSync
3) eglBindFramebuffer(ctx,0) it works on Amlogic but according to ARM is not guaranteed

Created simple test app (from essos-sample sources) that renders into texture backed FBO in separate thread and then draws this texture into a screen in the main thread.
[essos_mutithread_realtek.zip](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/12001021/essos_mutithread_realtek.zip)
As a result there is nothing drawn into the screen unless I use any of direct sync methods. glFlush() doesn't help here. What is more glFinish() is context related so must be called on the same thread that drawing operations happened. So it is not enough to call glFinish() on the main thread just before drawing into the screen, but we need to also call it on rendering thread once all drawing operations were called/scheduled. Then rendering into a screen also requires glFinish() to make sure the texture won't be changed/invalidated before it was really displayed.
This seems to be valid for both Amlogic and Realted devices.

Another point is that glSync/eglSync is not available for all platforms and depends on versions or extensions. Here. both Amlogic and Realtek seem to support this

**Comment by magomez** [comment]
There's a bit of mix of things in this issue. I'll try to go one by one.

First, a small explanation about opengl and thread syncronization:
* OpenGL/GLES don't have thread syncronization per se. They don't do it automatically. What they do is provide some tools so those using OpenGL/GLES can synchronize their threads.
* When we render with OpenGL/GLES, we render into a glContext by issuing gl commands. Each of this contexts has a buffer where they store those commands. We can't assume that those commands are sent to the GPU as soon as they are called, as they may be stored for optimizations and sent to the GPU later.
* The GPU has a single buffer to store the commands that it has to process.
* When there's more than one context issuing commands (with several threads, a context per thread is needed), the developer needs to be careful in order to ensure that the commands are executed in the order that they are intended. In your example, this means ensuring that the thread that renders to the texture has finished its operations before the thread that puts the texture to the display accesses the texture.
* There are several ways to perform this synchronization, but we have limited options because we use GLES2 to render, and many of the synchronization options were added on GLES3.

On GLES2 there are only two official options to perform this synchronization: glFlush() and glFinish(). These need to be called inside a context, after the requited gl commands have been issued, to ensure that any gl command that's executed after them is really being executed after them:

* glFlush(): this causes the commands stored in the context to be flushed to the GPU command buffer. As there's a single GPU command buffer, any gl command that's executed after this, no matter the thread, will be executed in the proper order. In your example, calling glFlush() after the texture has been rendered in the secondary thread and then notifying the main thread to display the texture content will ensure that the texture will have its content completed.

* glFinish(): this has the same effect than glFlush() but it also blocks until all the commands that have been flushed have been executed.  As in the previous case, any gl operation scheduled after this is guaranteed to be executed after the commands that were pushed to the GPU buffer. But as this waits until the operations are done, it's slower than glFlush(), so it's not used very often.

Bear in mind that if you don't use any of these commands, it may happen that the secondary thread may have performed some gl calls, but they are still in the context buffer. If at that point the main thread tries to access the texture, it's possible that the main thread gl commands are executed before the commands of the secondary thread. Or the commands could be mixed up in the GPU command buffer when their contexts decide to push them.

From our discussions in other issues and this one, it seems that the GLES implementation that Realtek and Amlogic are using has some problem and glFlush() is not working. Which means that, officially, we only have the option of glFinish(), which seems to work, but it reduces the performance a lot.

The option that you mention of glBindFramebuffer is not something that's officially supported. It's true that on some platforms, changing the bound framebuffer causes all the pending operations over the old framebuffer to be flushed, kinda like calling glFlush() or glFinish(). On some other platforms this happens when changing the texture that's attached to the framebuffer as well (despite we're doing this now on WPE and doesn't seem to work for your platforms).

The only option that I see feasible to fix the problem on your platforms is using glFinish(). The change should be simple, just calling glFinish() instead of glFlush() in a couple of places should do the trick. But we need some flag to enable this. Are you building for those platforms with -DUSE_PLATFORM_AMLOGIC and -DUSE_PLATFORM_REALTEK? (I think the latter one is not complete, I can add it).
Would it be enough calling glFinish() instead of glFlush() when those platforms are used? That should fix both the accelerated canvas and webgl issues.

I have a doubt about the webgl and canvas issues you mention though, and it's that you explicitly say that they happen with threaded rendering. I'm not sure if you mean rendering with threads in general, or if you refer explicitly to the threaded rendering feature that WPE has (the one enabled by setting some value to WEBKIT_NICOSIA_PAINTING_THREADS). Because the threaded rendering feature doesn't have anything to do with gl paintings, so it would be weird if they are related.

**Comment by asurdej-comcast** [comment]
@magomez Thaks for you input.
```
I have a doubt about the webgl and canvas issues you mention though, and it's that you explicitly say that they happen with threaded rendering. I'm not sure if you mean rendering with threads in general, or if you refer explicitly to the threaded rendering feature that WPE has (the one enabled by setting some value to WEBKIT_NICOSIA_PAINTING_THREADS). Because the threaded rendering feature doesn't have anything to do with gl paintings, so it would be weird if they are related.
```
It is about rendering in more than one thread in genera, especially like canvas where we draw into a texture in one thread and draw this texture into a screen on a different thread (I suppose webgl works pretty much the same). I'm not aware of any more threads unless Cairo does similar internally

```
The option that you mention of glBindFramebuffer is not something that's officially supported. It's true that on some platforms, changing the bound framebuffer causes all the pending operations over the old framebuffer to be flushed, kinda like calling glFlush() or glFinish(). On some other platforms this happens when changing the texture that's attached to the framebuffer as well (despite we're doing this now on WPE and doesn't seem to work for your platforms).
```
Not sure how about changing textures but binding different framebuffer seems to work in my test app. Didn't try that with webkit though. Do we have this in webkit?

```
Would it be enough calling glFinish() instead of glFlush() when those platforms are used? That should fix both the accelerated canvas and webgl issues.
```
On Realtek it fixes webgl blinking issue but not canvas. Maybe there is something more in cairo internals that is the reason here (realtek uses cairo 1.16, already tried with glesv2 and glesv3 - from different PR)
I will also confirm this with Amlogic device.

I will also try  to chase Amlogic and Realtek for this glFlush(). Amlogic stated that "rendering to texture" is not finished even after glFlush() and it seems to be never finished without glFinish() that could be against the GL spec

**Comment by magomez** [comment]
> It is about rendering in more than one thread in genera, especially like canvas where we draw into a texture in one thread and draw this texture into a screen on a different thread (I suppose webgl works pretty much the same). I'm not aware of any more threads unless Cairo does similar internally
> 

Ok, you're talking about a general case and not the concrete feature. Great.

> Not sure how about changing textures but binding different framebuffer seems to work in my test app. Didn't try that with webkit though. Do we have this in webkit?

We don't change the framebuffers in wpe because we don't need to. But if doing so we can get a behavior equivalent to calling glFlush, we could do it. Is this for Realtek, Amlogic or both?

> Would it be enough calling glFinish() instead of glFlush() when those platforms are used? That should fix both the accelerated canvas and webgl issues.
> 
> On Realtek it fixes webgl blinking issue but not canvas. Maybe there is something more in cairo internals that is the reason here (realtek uses cairo 1.16, already tried with glesv2 and glesv3 - from different PR) I will also confirm this with Amlogic device.

mmmmm let's do something. I'll prepare a patch that uses glFinish() both for the canvas and webgl. It should fix the issues for both. Then, if that works, we can try something more optimized by trying the framebuffer change. But in order to do this the platforms need to be differentiated by building with -DUSE_PLATFORM_AMLOGIC and -DUSE_PLATFORM_REALTEK.
 
> I will also try to chase Amlogic and Realtek for this glFlush(). Amlogic stated that "rendering to texture" is not finished even after glFlush() and it seems to be never finished without glFinish() that could be against the GL spec

Yes, you're not guaranteed that after the call to glFlush() the render to texture is finished, that's true. But it guarantees that any command launched after that (from the same thread or another) will be executed after the rendering command. And what the platform must guarantee is that, once the command to render the texture has been flushed, any command after that that tries to access the texture content must access the result of the rendering command, and not any intermediate step.

**Comment by asurdej-comcast** [comment]
```
We don't change the framebuffers in wpe because we don't need to. But if doing so we can get a behavior equivalent to calling glFlush, we could do it. Is this for Realtek, Amlogic or both?
```
I think it worked for both but didn't use Amlogic for some time so need to confirm.

```
mmmmm let's do something. I'll prepare a patch that uses glFinish() both for the canvas and webgl. It should fix the issues for both. Then, if that works, we can try something more optimized by trying the framebuffer change. But in order to do this the platforms need to be differentiated by building with -DUSE_PLATFORM_AMLOGIC and -DUSE_PLATFORM_REALTEK.

```
We use it for AMLOGIC only I think but not for Realtek. Usually we use PLATFORM(REALTEK) that is translated to WTF_PLATFORM_REALTEK.
I created a change that basically replaces all instances of glFlush() with glFinish() but canvas issue is still there for Realtek. Amlogic build should be ready soon

**Comment by asurdej-comcast** [comment]
Tried the same change (replace glFlush() with glFinish()) with Amlogic and it fixes both issues canvas and webgl. In case of canvas Realtek uses cairo 1.16 vs Amlogic 1.14 so maybe there are some differences in cairo. I will try to confirm both with the same configuratoin.

FBO binding also seems to work with Amlogic.

**Comment by magomez** [comment]
I'm loosing track of what works where, let me please recap:
- Realtek:
  - glFinish() fixes webgl but not canvas.
  - replacing the framebuffer fixes both cases.
- Amlogic:
  - glFinish() fixes both canvas and webgl.
  - replacing the framebuffer fixes both cases.

If my summary is correct, I can create a patch for those platforms that perform the framebuffer change instead of a glFlush. I'll work on this and send it next week.

Couple of comments:
- We need the build to use -DUSE_PLATFORM_AMLOGIC and -DUSE_PLATFORM_REALTEK to distinguish those platforms in order for this framebuffer change to be performed.
- Amlogic should definitely upgrade to cairo 1.16, cause cairo 1.14 has some know issues.

**Comment by asurdej-comcast** [comment]
Correct for glFinish() but didn't try webkit with fbo binding, only sample test application.

Realtek is the only device we have with cairo 1.16, all the rest still uses 1.14. Indeed we need to upgrade

**Comment by magomez** [comment]
@asurdej-comcast which version are you using to test? 2.28? 2.38? I want to create a patch so you can easily test the different options.

**Comment by asurdej-comcast** [comment]
the latest 2.38

**Comment by magomez** [comment]
@asurdej-comcast please give a try to the patch I'm attaching. It allows deciding on runtime which kind of gl synchonization is used through the WPE_GL_SYNC_METHOD env var. If the env var is not set, it will use the current glFlush() option. If it's set to 1, it will use glFinish() instead. If it's set to 2 it will use the trick of replacing the framebuffer. Whatever value is set, you'll see a log message in the console stating which method is used.

Please test the different options in your platforms and tell me which ones work and which ones don't. With that information I'll be able to craft a definitive patch that takes into account the best solution for each of the platforms.

Also, please, be sure to update to cairo 1.16 those platforms that have 1.14. It's possible that the canvas issues are coming from that.

[choose-gl-sync-method.patch.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/12081059/choose-gl-sync-method.patch.txt)

**Comment by magomez** [comment]
Ah, also keep an eye on the performance differences between using glFinish and the framebuffer trick, as we want to implement the most efficient approach!

**Comment by asurdej-comcast** [comment]
Spent some time testing with Amlogic and Realtek and here are the results:
1) webgl is fixed with glFinish() only on both platforms
2) canvas is fixed on Amlogic only with both glFinish() and glBindFramebuffer()
3) canvas issue on Realted is still there for glFlush, glFinish and glBindFramebuffer

Tested with:
1) Simple canvas page https://asurdej-comcast.github.io/canvas.html
2) webgl https://webglsamples.org/dynamic-cubemap/dynamic-cubemap.html
3) webgl https://webglsamples.org/field/field.html
4) Ihear radio app -> webgl

Didn't spot much performance difference in webgl between glFlush and glBindFramebuffer(). Blinking was there on both. With glFinish() performance dropped like 30%.

I need to run some more tests with canvas and performance ones.

BTW there was a change recently merged that made canvas accelerated only for canvases bigger than 1/4 of screen and it's actually fixing most of our canvas issues (as usually those are small ones)

**Comment by magomez** [comment]
@asurdej-comcast did you have a chance to perform the remaining tests with the patch that I sent you? So far we have these fixes for the issues:

* realtek
  * webgl: glFinish
  * canvas: nothing so far
* amlogic
  * webgl: glFinish
  * canvas: glFinish, glBindFramebuffer

I find quite weird that glFinish on realtek fixes the webgl issues but not the canvas ones, as the same approach should fix both.

**Comment by asurdej-comcast** [comment]
Hi, no updates yet, got stuck in other tasks. I have Amlogic buidl with updated cairo 1.16 ready so will try to provide the results soon

**Comment by asurdej-comcast** [comment]
@magomez Sorry for the delay, I've just tried this with Amlogic + cairo 1.16 and the results are the same as with realtek -> there is no cure for canvas, neither glFinish nor glBuidFramebuffer work (both worked with cairo 1.14)

In case of webgl, only glFinish seems to help, at least with tests that I have. The issue is not visible with all webgl tests
Here some performance results on different simple test cases:
1) issue highly reproducible -> https://webglsamples.org/dynamic-cubemap/dynamic-cubemap.html ~40fps VS ~30fps
2) quite reproducible https://webglsamples.org/field/field.html 28fps VS 22 fps
3) issue not visible at all http://luic.github.io/WebGL-Performance-Benchmark/benchmark/cubes.html 620cubes vs 250cubes

So now we have the same results for both platforms:
1) webgl: glFinish
2) canvas: nothing

I'm keeping this low priority as webgl is only visible with one app: iHeart radio. Lightning framework has some workaround for this like read pixels or so
In case of canvas this is only an issue for single updates as the result may not be visible on first draw but on second one (if redraw is done twice). With the change that forces accelerated canvas for size >= 1/4screen most our issues are fixed as they don't reach the limit

**Comment by magomez** [comment]
@asurdej-comcast which versions of cairo are those platforms using and which gles versions is cairo being built for? Are you using cairo 1.6 with the GLES2 version? Or are you using any other variant? Cairo 1.16 with GLESv2 is the one that's tested and supported. Any other configuration may have unexpected issues. I'm not sure whether it's related or not, but I told you in https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/1116 that cairo with GLES3 was not tested.

**Comment by asurdej-comcast** [comment]
Amlogic has cairo-1.16 with glesv2
realtek uses cairo-1.16 and glesv3

**Comment by asurdej-comcast** [comment]
Hi @magomez I made some performance comparison on webgl for Amlogic and Realtek platforms taking into account three cases:
1) glFlush() as it is in the code by default
2) glFinish() as you proposed
3) GLsync - draft PR https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/1202 based on https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/976

Note, this focuses on webgl only.
Tested with couple of examples from www.webglsamples.org:
https://webglsamples.org/dynamic-cubemap/dynamic-cubemap.html
https://webglsamples.org/field/field.html
https://webglsamples.org/spacerocks/spacerocks.html
https://webglsamples.org/multiple-views/multiple-views.html
https://webglsamples.org/fishtank/fishtank.html
https://webglsamples.org/google-io/2011/1000-objects-optimized.html
https://webglsamples.org/aquarium/aquarium.html

With no changes I'm seeing different artifacts, like black screen blinking, jerking animations (going back and forth), etc
Both glFinish() and GLsync make this disapear.

But GLsync seems to have come with less performance drop than glFinish(). Below you can see rough comparison of average FPS value for each example. Background color mans pass/fail.
![webgl_performance](https://github.com/WebPlatformForEmbedded/WPEWebKit/assets/101130014/c2f0aebe-a35f-42ac-975e-f38d3955b6f3)

Created draft PR for GLsync https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/1202 that is based on https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/976 with some of your comments fixed.
Still need to rebuild and verify with different platform to make sure nothing is broken.

**Comment by magomez** [comment]
@asurdej-comcast , before you keep writing lines of code to try to fix the webgl case. Are you planning to use nonCompositedWebGL on those platforms? Cause if you're testing webgl to use lightning, then you should use that flag and none of those issues should be reproducible.
If you plan to launch webgl content that's not lightning then yes, we can continue looking into this.

**Comment by asurdej-comcast** [comment]
@magomez We use nonCompositedWebGL for Lightning apps already and it works fine indeed.
But we still have non-lightning apps that use webgl and we don't use non composited webgl in such case

**Comment by magomez** [comment]
@asurdej-comcast I've been doing some experiments on how to use fences without having to use platform guards, as you do in your PR. I've come up with something that may work by using fences only when the context gotten is version 3 or higher. I've tested in on the rpi (GLES2 only) and it builds there, but of course it doesn't use fences. It should build for your platforms as well, as they have GLES3 there. Could you give a test to this patch? It's an early version, but it should work for WebGL. If you confirm that it fixes the issues for your platforms, I'll add a way to fix the same problem with the canvas (despite the artifacts may come from other places and not just this synchronization).

[use_fences_if_possible.patch.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/12803145/use_fences_if_possible.patch.txt)

**Comment by magomez** [comment]
Ah, the patch will output some messages to the console indicating whether it's using fences for sync or not using anything.

**Comment by asurdej-comcast** [comment]
Thanks, it looks good on Amlogic device. Still waiting for Realtek build to verify but I don't expect much difference.

In my patch I enabled sync build option based on platform indeed but in fact it would be even better to just leave it as a build option so we can enable it at build environment level (in yocto) for specific devices and don't do any platform guards inside webkit

**Comment by magomez** [comment]
> Thanks, it looks good on Amlogic device. Still waiting for Realtek build to verify but I don't expect much difference.

Great!
 
> In my patch I enabled sync build option based on platform indeed but in fact it would be even better to just leave it as a build option so we can enable it at build environment level (in yocto) for specific devices and don't do any platform guards inside webkit

I'm afraid I'm a bit confused here on whether you want to have platform guards or not. You say that you prefer a build option but then you don't want to do platform guards in wpe... if we have a build option then we need platform guards to build with or without the feature.

When you confirm that my patch works fine on Realtek as well, I'll implement a fix for all the platforms using a similar approach, including the canvas. But I don't plan to add glFinish calls when fences are not available. I'll use just glFlush. I hope that should be enough to fix all the platforms without having a performance regression. If that's not the case, then I'll have to add glFinish.

If you want to have platform guards, then let me finish and commit this patch, and then we can add them for your platforms. The patch will be way easier this way.

**Comment by asurdej-comcast** [comment]
I ment that we can just have a build option like USE_FORCE_WEBGL_BUFFER_SYNC that will be disabled by default inside webkit for all platfomrs (so no platform dependency here). Then I can enable it at build time for specific bitbake recipe for specific device that I will be sure it supports glsync.

I other words we can remove platform dependent parts from my patch:
```
if (USE_WPEWEBKIT_PLATFORM_REALTEK OR USE_WPEWEBKIT_PLATFORM_AMLOGIC)
    if (USE_NICOSIA AND USE_COORDINATED_GRAPHICS AND USE_TEXTURE_MAPPER)
        SET_AND_EXPOSE_TO_BUILD(USE_FORCE_WEBGL_BUFFER_SYNC TRUE)
    endif ()
endif ()

```
and replace it with simple option declaration, like:
```
WEBKIT_OPTION_DEFINE(USE_FORCE_WEBGL_BUFFER_SYNC "Enable glsync" PUBLIC OFF)
```


No glFinish() should be good. I see this issue on Aml and Rtk that both have glSync.

**Comment by magomez** [comment]
As I'm going to implement it, it will be a runtime check. If the platform supports fences, they will be used, and if not, then just glFlush is done. This doesn't add any dependency on any platform, and we don't need any build option, and this will be the default behavior for all platforms. I'm not sure I get why you need the build option.

**Comment by asurdej-comcast** [comment]
Just tested with realtek and your patch works fine. So it is good with both amlogic and realtek, both printing:
```
Oct 11 08:13:12 skyxione WPEFramework[26875]: using fences
Oct 11 08:13:12 skyxione WPEFramework[26875]: using fences
Oct 11 08:13:12 skyxione WPEFramework[26875]: using fences
Oct 11 08:13:12 skyxione WPEFramework[26875]: using fences
```

Regarding build option, how about devices that support glSync but don't have this sync issue at alll. I'm thinking about broadcom mainly that works fine as is and doesn't require any addional sync. Such patch may cause performance drop with no gain in return. This is my only concern for hiding this behind a build option. (but I'm not even sure if broadcom supports fences...)

**Comment by magomez** [comment]
> Just tested with realtek and your patch works fine. So it is good with both amlogic and realtek, both printing:

Great! I'll prepare a patch that includes the canvas as well.
 
> Regarding build option, how about devices that support glSync but don't have this sync issue at alll. I'm thinking about broadcom mainly that works fine as is and doesn't require any addional sync. Such patch may cause performance drop with no gain in return. This is my only concern for hiding this behind a build option. (but I'm not even sure if broadcom supports fences...)

There shouldn't be any performance drop on those platforms. If they are working fine without any sync, then the sync won't cause any extra wait. But if there's indeed a performance drop, I prefer to add the build option to disable the sync at that point, once we're sure there's a problem.

**Comment by asurdej-comcast** [comment]
Great, sounds good to me, thanks

**Comment by asurdej-comcast** [comment]
Hi @magomez Not really connected to this issue but do you maybe know any good webgl and canvas 2d tests, functional and performance. Currently mainly interested in 2d canvas performance as the once that I'm using are not really reliable

**Comment by magomez** [comment]
> Hi @magomez Not really connected to this issue but do you maybe know any good webgl and canvas 2d tests, functional and performance. Currently mainly interested in 2d canvas performance as the once that I'm using are not really reliable

I usually use https://www.smashcat.org/av/canvas_test/ to test performance. Then I have a couple of custom tests for concrete cases that I want to keep an eye on, and test some of the game s in the sky portal for functionality.

**Comment by magomez** [comment]
@asurdej-comcast I've just pushed a couple of commits to wpe-2.38 (bd90673616f09f598b8722341fafa4323f873dbe and 2deb4161ca87e2b4cb77a7133b76243f947e1b5f). The first one fixes an issue that I found while trying to add the fences to the canvas content, and the second one adds when fences when available, both for canvas and webgl content.

Could you give the changes a try and close this if the problems are fixed? thanks in advance!

**Comment by asurdej-comcast** [comment]
@magomez Thanks. Tested with Amlogic and Realtek and both seem to work fine. There are no more webgl blinks that is the main issue currently.
For canvas 2d issue (point 2) from description) that is drawing the previous image instead of current one, the issue is still there but I used to live with it already. Most of our use cases are either dynamic (so it is not a problem) or small enough to use unaccelerated canvas. glFinish()/sync was helping for prev cairo 1.14 (or 1.12 not sure) version but after updating cairo to 1.16 this is back again and nothing seems to help now. I will spend some time to check what is the problem here as I have another acc canvas issue, copyToPlatformTexture(), that results with black rectangle instead of actual image in some cases (visible in one app). We are considering disabling acc 2d canvas but I'm pretty afraid of the performance drop.

Btw, I can see last line commented out in below code while the comment states opposite:
```
    if (m_nicosia.contentLayer) {
        // The call to swapBuffersIfNeeded will cause that WebGL and acc canvas push a new buffer to their proxy.
        // They won't request a composition with this new buffer, so we need to ensure that the composition is
        // triggered in case no other component does it.
        downcast<Nicosia::ContentLayerTextureMapperImpl>(m_nicosia.contentLayer->impl()).swapBuffersIfNeeded();
        // m_nicosia.performLayerSync |= true;
    }
```

**Comment by magomez** [comment]
> @magomez Thanks. Tested with Amlogic and Realtek and both seem to work fine. There are no more webgl blinks that is the main issue currently. 

Ok, at least something positive.

> For canvas 2d issue (point 2) from description) that is drawing the previous image instead of current one, the issue is still there but I used to live with it already. Most of our use cases are either dynamic (so it is not a problem) or small enough to use unaccelerated canvas. glFinish()/sync was helping for prev cairo 1.14 (or 1.12 not sure) version but after updating cairo to 1.16 this is back again and nothing seems to help now. I will spend some time to check what is the problem here as I have another acc canvas issue, copyToPlatformTexture(), that results with black rectangle instead of actual image in some cases (visible in one app). We are considering disabling acc 2d canvas but I'm pretty afraid of the performance drop.
> 
> Btw, I can see last line commented out in below code while the comment states opposite:
> 
> ```
>     if (m_nicosia.contentLayer) {
>         // The call to swapBuffersIfNeeded will cause that WebGL and acc canvas push a new buffer to their proxy.
>         // They won't request a composition with this new buffer, so we need to ensure that the composition is
>         // triggered in case no other component does it.
>         downcast<Nicosia::ContentLayerTextureMapperImpl>(m_nicosia.contentLayer->impl()).swapBuffersIfNeeded();
>         // m_nicosia.performLayerSync |= true;
>     }
> ```

OMG I completely forgot about uncommenting that line! I already pushed a new commit fixing it. This could perfectly explain why this problem of the canvas drawing the previous image instead of the current one is still there. I didn't try your test to check it (I forgot about it), but tried a couple of others that had the same problem and they were fixed, so I suspect with this change it will be fixed for you as well. Can you give it a try? So sorry for the mistake.

I understand that you're thinking of disabling the acc canvas. It's something that is my mind as well. Stabilizing it for each of the platforms is quite complicated, and now that's not upstream and needs to be added for each release, it's getting more and more difficult. But let's give it a last try. I have good hopes about this fix.

The copyToPlatforTexture issue could be related to https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/1131, which I'm working on.

**Comment by asurdej-comcast** [comment]
Uncommenting that line didn't make much difference for canvas 2d, the issue is still there.It only happens with Amlogic/realtek only and works perfectly fine with broadcom so looks like yet another mali driver specific.

On copyToPlatforTexture() in my case putPixelBuffer is not used at all. It is pure canvas texture to webgl texture copy. And in fact I replaced texture copy with direct drawing on webgl "destinationTexture" (with glTexImage2D and raw pixel data) and the result is the same (black rectangle that is replaced with actual image eventually). Switching to offscreen context seems to be problematic here as drawing in webgl context looks good. Still other use cases for this texImage2D with acc canvas works fine so there must be something more. And also mali driver specific.
As a quick fix I disabled copyToPlatformTexutre() (quick "return false") so it uses more software fallback but looks much better.

btw From 2.38 copyToPlatformTexutre():
```
    if (!premultiplyAlpha || flipY)
        return false;
```
In 2.28 alpha condition is flipped that makes more sense to me as we need to do pre-multiplicaton of alpha :
```
    if (premultiplyAlpha || flipY)
        return false;
```
Is that correct?

**Comment by magomez** [comment]
@asurdej-comcast , I've just pushed a couple of commits that restrict the conditions required to accelerate the canvases. This should prevent that canvases that are used together with WebGL are accelerated, which should remove your problem with copyToPlatforTexture. I've also removed the implementation of copyToPlatformTexture as well, as it won't be used. Could you give it a test and check whether the problem is fixed? If so, please close this issue.

**Comment by magomez** [comment]
GL synchronization has been added and the issue with copyToPlatformTexture won't reproduce anymore as WebGL won't be able to use accelerated canvases, so closing this.

**Comment by asurdej-comcast** [comment]
Thanks @magomez, We've updated our repo recently to include all the latest changes. No major regresion found so far. Thanks
