### ISSUE TITLE
Certificates and websockets

### ISSUE THREAD

**Issue by depili** [Metrological/WebKitForWayland#2]
Currently wpe fetches any and all content over https just fine regardless of certificates. But when it comes to websocket connections the behavior is reversed, and the connection fails, even if the server has a valid certificate, because no root certs are included.

This is from the wpe console when trying to open a secure (wss://) websocket:
```
´(WPEWebProcess:616): GLib-Net-WARNING **: couldn't load TLS file database: Failed to open file '/etc/ssl/certs/ca-certificates.crt': No such file or directory
CONSOLE ERROR WebSocket network error: Unacceptable TLS certificate
```

**Comment by albertd** [comment]
Solved in https://github.com/Metrological/buildroot/commit/f25205b16b3df06056d911b0c1a662ccdd84cb82

**Comment by SteffenDE** [comment]
I'm still encountering this error :(
![bildschirmfoto 2018-03-09 um 19 05 11](https://user-images.githubusercontent.com/4116351/37222298-d682bb3e-23cc-11e8-9029-d027bbc30ee4.png)
